[package]
name = "mini-grep-trpl"
version = "0.1.0"
edition = "2021"

[lib]
name = "mini_grep_functions"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
